spring.application.name=travelmate-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/travelmate}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:21052026}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=${APP_JWT_SECRET:TravelMateJwtSecretKeyTravelMateJwtSecretKeyTravelMateJwtSecretKey}
app.jwt.access-token-minutes=${APP_JWT_ACCESS_TOKEN_MINUTES:120}
app.jwt.refresh-token-days=${APP_JWT_REFRESH_TOKEN_DAYS:30}