spring:
  datasource:
    # URL trỏ đến service 'postgres' trong docker-compose
    url: jdbc:postgresql://postgres:5432/travelmate
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      # Dùng 'update' để giữ dữ liệu, hoặc 'create' nếu muốn xóa sạch khi khởi động lại
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  # Cấu hình Mail (giả lập)
  mail:
    host: localhost
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
openweathermap:
  api:
    url: ${OPENWEATHERMAP_API_URL:https://api.openweathermap.org/data/2.5}
    key: ${OPENWEATHER_API_KEY:}

gemini:
  api-key: ${GEMINI_API_KEY:{GEMINI_API_KEY}}
  url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

ai-service:
  url: ${AI_SERVICE_URL:http://host.docker.internal:8000}

# Cấu hình Springdoc (Swagger UI)
springdoc:
  # Đường dẫn để truy cập Swagger UI
  swagger-ui:
    path: /swagger-ui.html
  # Các đường dẫn API sẽ được quét
  paths-to-match:
    - /api/**
