spring:
  datasource:
    # URL trỏ đến service 'postgres' trong docker-compose
    url: jdbc:postgresql://postgres:5432/travelmate
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      # Dùng 'update' để giữ dữ liệu, hoặc 'create' nếu muốn xóa sạch khi khởi động lại
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  # Cấu hình Mail (giả lập)
  mail:
    host: localhost
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
